import type { Question } from "./storage.js";

/**
 * Default question bank — 50 questions across 5 categories. Used when a chat
 * has no custom questions. Every question has exactly 4 choices and a correct
 * 0-based index.
 */
export const DEFAULT_QUESTIONS: Question[] = [
  // ── Science (10) ────────────────────────────────────────────────────────────
  {
    category: "Science",
    text: "What is the chemical symbol for water?",
    choices: ["H2O", "CO2", "O2", "NaCl"],
    correctId: 0,
    sourceType: "default",
    explanation: "Water is H₂O — two hydrogen atoms and one oxygen.",
  },
  {
    category: "Science",
    text: "What planet is known as the Red Planet?",
    choices: ["Venus", "Jupiter", "Mars", "Saturn"],
    correctId: 2,
    sourceType: "default",
    explanation: "Mars gets its red color from iron oxide (rust) on its surface.",
  },
  {
    category: "Science",
    text: "What gas do plants absorb from the atmosphere?",
    choices: ["Oxygen", "Nitrogen", "Hydrogen", "Carbon dioxide"],
    correctId: 3,
    sourceType: "default",
    explanation: "Plants use CO₂ in photosynthesis to produce oxygen.",
  },
  {
    category: "Science",
    text: "What is the speed of light in a vacuum?",
    choices: ["300,000 km/s", "150,000 km/s", "500,000 km/s", "100,000 km/s"],
    correctId: 0,
    sourceType: "default",
    explanation: "Light travels at ~299,792 km/s, roughly 300,000 km/s.",
  },
  {
    category: "Science",
    text: "What is the largest organ in the human body?",
    choices: ["Liver", "Brain", "Skin", "Heart"],
    correctId: 2,
    sourceType: "default",
    explanation: "Skin is the body's largest organ by surface area and weight.",
  },
  {
    category: "Science",
    text: "How many bones are in the adult human body?",
    choices: ["186", "206", "226", "256"],
    correctId: 1,
    sourceType: "default",
    explanation: "The adult human skeleton has 206 bones.",
  },
  {
    category: "Science",
    text: "What element has the atomic number 1?",
    choices: ["Helium", "Lithium", "Hydrogen", "Oxygen"],
    correctId: 2,
    sourceType: "default",
    explanation: "Hydrogen is the lightest element with atomic number 1.",
  },
  {
    category: "Science",
    text: "What type of animal is a dolphin?",
    choices: ["Fish", "Reptile", "Amphibian", "Mammal"],
    correctId: 3,
    sourceType: "default",
    explanation: "Dolphins are warm-blooded mammals that breathe air.",
  },
  {
    category: "Science",
    text: "What is the powerhouse of the cell?",
    choices: ["Nucleus", "Ribosome", "Mitochondria", "Membrane"],
    correctId: 2,
    sourceType: "default",
    explanation: "Mitochondria produce ATP — the cell's energy currency.",
  },
  {
    category: "Science",
    text: "What is the boiling point of water in Celsius?",
    choices: ["90°C", "95°C", "100°C", "110°C"],
    correctId: 2,
    sourceType: "default",
    explanation: "Water boils at 100°C at standard atmospheric pressure.",
  },

  // ── History (10) ──────────────────────────────────────────────────────────
  {
    category: "History",
    text: "In which year did World War II end?",
    choices: ["1943", "1944", "1945", "1946"],
    correctId: 2,
    sourceType: "default",
    explanation: "WWII ended in 1945 with Germany's surrender in May and Japan's in September.",
  },
  {
    category: "History",
    text: "Who was the first President of the United States?",
    choices: ["Thomas Jefferson", "John Adams", "George Washington", "Benjamin Franklin"],
    correctId: 2,
    sourceType: "default",
    explanation: "George Washington served as the first US president from 1789–1797.",
  },
  {
    category: "History",
    text: "Which ancient civilization built the pyramids?",
    choices: ["Romans", "Greeks", "Egyptians", "Persians"],
    correctId: 2,
    sourceType: "default",
    explanation: "The ancient Egyptians built the pyramids as tombs for pharaohs.",
  },
  {
    category: "History",
    text: "What ship sank in 1912?",
    choices: ["Lusitania", "Titanic", "Britannic", "Olympic"],
    correctId: 1,
    sourceType: "default",
    explanation: "The RMS Titanic sank on its maiden voyage in April 1912.",
  },
  {
    category: "History",
    text: "Who painted the Mona Lisa?",
    choices: ["Michelangelo", "Raphael", "Leonardo da Vinci", "Donatello"],
    correctId: 2,
    sourceType: "default",
    explanation: "Leonardo da Vinci painted the Mona Lisa in the early 1500s.",
  },
  {
    category: "History",
    text: "What ancient empire was ruled by Julius Caesar?",
    choices: ["Greek", "Roman", "Persian", "Ottoman"],
    correctId: 1,
    sourceType: "default",
    explanation: "Julius Caesar was a military leader and dictator of the Roman Republic.",
  },
  {
    category: "History",
    text: "In what year did the Berlin Wall fall?",
    choices: ["1987", "1988", "1989", "1990"],
    correctId: 2,
    sourceType: "default",
    explanation: "The Berlin Wall fell on November 9, 1989.",
  },
  {
    category: "History",
    text: "Which country first landed a human on the moon?",
    choices: ["Soviet Union", "United States", "China", "France"],
    correctId: 1,
    sourceType: "default",
    explanation: "The US Apollo 11 mission landed Neil Armstrong on the moon in 1969.",
  },
  {
    category: "History",
    text: "What was the name of the first successful vaccine for?",
    choices: ["Polio", "Smallpox", "Measles", "Rabies"],
    correctId: 1,
    sourceType: "default",
    explanation: "Edward Jenner developed the first vaccine against smallpox in 1796.",
  },
  {
    category: "History",
    text: "Which war was fought between the North and South in the US?",
    choices: ["Revolutionary War", "War of 1812", "Civil War", "Spanish-American War"],
    correctId: 2,
    sourceType: "default",
    explanation: "The American Civil War (1861–1865) was fought over slavery and states' rights.",
  },

  // ── Geography (10) ────────────────────────────────────────────────────────
  {
    category: "Geography",
    text: "What is the largest continent by area?",
    choices: ["Africa", "North America", "Asia", "Europe"],
    correctId: 2,
    sourceType: "default",
    explanation: "Asia is the largest continent at ~44.6 million km².",
  },
  {
    category: "Geography",
    text: "What is the longest river in the world?",
    choices: ["Amazon", "Nile", "Yangtze", "Mississippi"],
    correctId: 1,
    sourceType: "default",
    explanation: "The Nile is the longest river at ~6,650 km.",
  },
  {
    category: "Geography",
    text: "Which country has the most people?",
    choices: ["India", "United States", "China", "Indonesia"],
    correctId: 0,
    sourceType: "default",
    explanation: "India surpassed China in 2023 to become the most populous country.",
  },
  {
    category: "Geography",
    text: "What is the capital of Japan?",
    choices: ["Osaka", "Kyoto", "Tokyo", "Seoul"],
    correctId: 2,
    sourceType: "default",
    explanation: "Tokyo has been Japan's capital since 1868.",
  },
  {
    category: "Geography",
    text: "What ocean is on the west coast of the United States?",
    choices: ["Atlantic", "Pacific", "Indian", "Arctic"],
    correctId: 1,
    sourceType: "default",
    explanation: "The Pacific Ocean borders the US west coast.",
  },
  {
    category: "Geography",
    text: "What is the smallest country in the world?",
    choices: ["Monaco", "San Marino", "Vatican City", "Liechtenstein"],
    correctId: 2,
    sourceType: "default",
    explanation: "Vatican City is the world's smallest country at just 0.44 km².",
  },
  {
    category: "Geography",
    text: "Which desert is the largest hot desert?",
    choices: ["Gobi", "Kalahari", "Sahara", "Arabian"],
    correctId: 2,
    sourceType: "default",
    explanation: "The Sahara spans ~9.2 million km² across North Africa.",
  },
  {
    category: "Geography",
    text: "What is the tallest mountain in the world?",
    choices: ["K2", "Kangchenjunga", "Mount Everest", "Lhotse"],
    correctId: 2,
    sourceType: "default",
    explanation: "Mount Everest stands at 8,849 meters above sea level.",
  },
  {
    category: "Geography",
    text: "How many continents are there on Earth?",
    choices: ["5", "6", "7", "8"],
    correctId: 2,
    sourceType: "default",
    explanation: "There are 7 continents: Africa, Antarctica, Asia, Australia, Europe, North America, South America.",
  },
  {
    category: "Geography",
    text: "What country is known as the Land of the Rising Sun?",
    choices: ["China", "South Korea", "Thailand", "Japan"],
    correctId: 3,
    sourceType: "default",
    explanation: "Japan is called Nihon/Nippon — 'origin of the sun'.",
  },

  // ── Sports (10) ───────────────────────────────────────────────────────────
  {
    category: "Sports",
    text: "How many players are on a soccer team on the field?",
    choices: ["9", "10", "11", "12"],
    correctId: 2,
    sourceType: "default",
    explanation: "Each soccer team fields 11 players including the goalkeeper.",
  },
  {
    category: "Sports",
    text: "In which sport would you perform a slam dunk?",
    choices: ["Volleyball", "Tennis", "Basketball", "Handball"],
    correctId: 2,
    sourceType: "default",
    explanation: "A slam dunk is a basketball shot where the player jumps and forces the ball through the hoop.",
  },
  {
    category: "Sports",
    text: "How many rings are on the Olympic flag?",
    choices: ["3", "4", "5", "6"],
    correctId: 2,
    sourceType: "default",
    explanation: "The five rings represent the five inhabited continents.",
  },
  {
    category: "Sports",
    text: "What sport is played at Wimbledon?",
    choices: ["Cricket", "Golf", "Tennis", "Rugby"],
    correctId: 2,
    sourceType: "default",
    explanation: "Wimbledon is one of tennis's four Grand Slam tournaments.",
  },
  {
    category: "Sports",
    text: "In which country did judo originate?",
    choices: ["China", "Korea", "Thailand", "Japan"],
    correctId: 3,
    sourceType: "default",
    explanation: "Judo was created in Japan by Jigoro Kano in 1882.",
  },
  {
    category: "Sports",
    text: "What is the diameter of a basketball hoop in inches?",
    choices: ["16", "18", "20", "22"],
    correctId: 1,
    sourceType: "default",
    explanation: "A standard basketball hoop has an 18-inch diameter.",
  },
  {
    category: "Sports",
    text: "What color belt is the highest rank in karate?",
    choices: ["Red", "White", "Black", "Gold"],
    correctId: 2,
    sourceType: "default",
    explanation: "The black belt (dan) is the highest rank in karate.",
  },
  {
    category: "Sports",
    text: "How many bases are on a baseball field?",
    choices: ["3", "4", "5", "6"],
    correctId: 1,
    sourceType: "default",
    explanation: "There are 4 bases: first, second, third, and home plate.",
  },
  {
    category: "Sports",
    text: "Which country won the first FIFA World Cup in 1930?",
    choices: ["Argentina", "Brazil", "Uruguay", "Italy"],
    correctId: 2,
    sourceType: "default",
    explanation: "Uruguay won the first World Cup, hosting and defeating Argentina in the final.",
  },
  {
    category: "Sports",
    text: "What is a 'hat-trick' in cricket?",
    choices: ["3 runs", "3 wickets in 3 balls", "3 sixes", "3 catches"],
    correctId: 1,
    sourceType: "default",
    explanation: "A hat-trick is when a bowler takes three wickets in three consecutive deliveries.",
  },

  // ── Entertainment (10) ────────────────────────────────────────────────────
  {
    category: "Entertainment",
    text: "What is the name of Harry Potter's school?",
    choices: ["Durmstrang", "Beauxbatons", "Hogwarts", "Ilvermorny"],
    correctId: 2,
    sourceType: "default",
    explanation: "Hogwarts School of Witchcraft and Wizardry is where Harry Potter studies.",
  },
  {
    category: "Entertainment",
    text: "Who played Jack in Titanic (1997)?",
    choices: ["Brad Pitt", "Tom Cruise", "Leonardo DiCaprio", "Matt Damon"],
    correctId: 2,
    sourceType: "default",
    explanation: "Leonardo DiCaprio played Jack Dawson opposite Kate Winslet's Rose.",
  },
  {
    category: "Entertainment",
    text: "What is the highest-grossing film of all time?",
    choices: ["Avengers: Endgame", "Avatar", "Titanic", "Star Wars: The Force Awakens"],
    correctId: 1,
    sourceType: "default",
    explanation: "Avatar (2009) is the highest-grossing film with ~$2.9 billion worldwide.",
  },
  {
    category: "Entertainment",
    text: "Which band performed at the first-ever Live Aid in 1985?",
    choices: ["Queen", "The Beatles", "Led Zeppelin", "U2"],
    correctId: 0,
    sourceType: "default",
    explanation: "Queen's Live Aid performance is widely considered one of the greatest live shows ever.",
  },
  {
    category: "Entertainment",
    text: "What year was the first Star Wars film released?",
    choices: ["1975", "1977", "1979", "1980"],
    correctId: 1,
    sourceType: "default",
    explanation: "Star Wars (Episode IV: A New Hope) premiered in 1977.",
  },
  {
    category: "Entertainment",
    text: "Who created the Marvel Comics character Spider-Man?",
    choices: ["Jack Kirby", "Stan Lee & Steve Ditko", "Joe Simon", "Bob Kane"],
    correctId: 1,
    sourceType: "default",
    explanation: "Stan Lee and Steve Ditko created Spider-Man, debuting in Amazing Fantasy #15 (1962).",
  },
  {
    category: "Entertainment",
    text: "What TV series features the Iron Throne?",
    choices: ["The Witcher", "Lord of the Rings", "Game of Thrones", "Vikings"],
    correctId: 2,
    sourceType: "default",
    explanation: "Game of Thrones is based on George R.R. Martin's A Song of Ice and Fire.",
  },
  {
    category: "Entertainment",
    text: "What is the best-selling video game of all time?",
    choices: ["Tetris", "Minecraft", "GTA V", "Wii Sports"],
    correctId: 1,
    sourceType: "default",
    explanation: "Minecraft has sold over 300 million copies since its 2011 release.",
  },
  {
    category: "Entertainment",
    text: "Which actor played the Joker in The Dark Knight?",
    choices: ["Jack Nicholson", "Jared Leto", "Heath Ledger", "Joaquin Phoenix"],
    correctId: 2,
    sourceType: "default",
    explanation: "Heath Ledger won a posthumous Oscar for his portrayal of the Joker.",
  },
  {
    category: "Entertainment",
    text: "What is the name of the fictional city where Batman operates?",
    choices: ["Metropolis", "Star City", "Gotham", "Central City"],
    correctId: 2,
    sourceType: "default",
    explanation: "Batman protects Gotham City, while Superman watches over Metropolis.",
  },
];

/** Get all unique categories in the default question bank. */
export function defaultCategories(): string[] {
  const seen = new Set<string>();
  for (const q of DEFAULT_QUESTIONS) seen.add(q.category);
  return [...seen].sort();
}

/** Get default questions by category. */
export function defaultQuestionsByCategory(category: string): Question[] {
  return DEFAULT_QUESTIONS.filter((q) => q.category === category);
}